services:

  phaser-app: # frontend
    build: ./Dev/
    ports:
      - "8000:8000"
    restart: always
    networks: # Permet de communiquer uniquement avec le backend
      - dev_network
    mem_limit: 512m   # Limite de mémoire
    cpus: "0.5"       # Limite de CPU (50% d'un core)
    depends_on:
      - server

  server: # backend
    build: ./server/
    ports:
      - "3000:3000"
    restart: always
    networks: # Permet de communiquer avec le frontend et la bdd
      - dev_network
    mem_limit: 1g     # Limite de mémoire
    cpus: "1.0"       # Limite de CPU (1 core)
    logging:
      driver: "json-file"  # Spécifie le driver de log à utiliser
      options:
        max-size: "10m"    # Limite la taille du fichier de log
        max-file: "3"      # Limite le nombre de fichiers de log
    depends_on:
      - db

  db:  # base de données MySQL
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SAE_BRDGame # Mot de passe pour l'utilisateur root
      MYSQL_DATABASE: game_database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./bdd_SAE:/docker-entrypoint-initdb.d # Monte le dossier database/ pour init.sql
    networks:
      - dev_network

  phpmyadmin:  # interface de gestion MySQL
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db  # Le nom du service MySQL dans docker-compose.yml
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - dev_network 

volumes:
  db_data:

networks:
  dev_network:
    driver: bridge  # Le réseau dev_network utilise le driver 'bridge'

    