services:

  phaser-app: # frontend
    build: ./Dev/
    ports:
      - "8000:8000"
    restart: always
    networks: # Permet de communiquer uniquement au backend
      - server
    mem_limit: 512m   # Limite de mémoire
    cpus: "0.5"       # Limite de CPU (50% d'un core)

  server: # backend
    build: ./server/
    ports:
      - "3000:3000"
    restart: always
    networks: # Permet de communiquer avec le frontend et la bdd
      - Dev
    mem_limit: 1g     # Limite de mémoire
    cpus: "1.0"       # Limite de CPU (1 core)
    logging:
      driver: "json-file"  # Spécifie le driver de log à utiliser
      options:
        max-size: "10m"  # Limite la taille du fichier de log
        max-file: "3"    # Limite le nombre de fichiers de log
  
  #bdd:
  #  image:
  #  restart: always
  #  environment:
  #    - name=value
  #  volumes:
  #    - hostPath:containerPath:ro
  #  networks:
  #    - networkName
#volumes:
#  bdd:

networks:
  Dev:
    driver: bridge # Réseau de communication privé entre pls conteneurs
  server:
    driver: bridge # Réseau de communication privé entre pls conteneurs